services:
  redis-dev:
    image: redis:7-alpine
    container_name: swiftstore_redis_dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  redis_dev_data:
